### ISSUE TITLE
Do you any algorithm on PHP?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/php#1]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [PHP](https://github.com/AllAlgorithms/php) this case

**Comment by mathiasdonoso** [comment]
This sounds awesome, I will be working on some algorithms

**Comment by mathiasdonoso** [comment]
Should we be creating unit tests? Is a young project so is easy to implement test at this moment.

I think for adding tests, we can use a project structure using the folders: src and tests.
